from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping

from .schema import QUEUE_DIRECTORIES


def ensure_queue_directories(queue_root: str | Path) -> Path:
    root = Path(queue_root)
    root.mkdir(parents=True, exist_ok=True)
    for directory in QUEUE_DIRECTORIES:
        (root / directory).mkdir(parents=True, exist_ok=True)
    return root


def write_json(path: str | Path, payload: Mapping[str, Any]) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return target


def write_text(path: str | Path, content: str) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return target


def utc_run_id() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def render_markdown_report(report: Mapping[str, Any]) -> str:
    lines = [
        "# Latest Codex Queue Dry-Run Report",
        "",
        f"- run_id: `{report['run_id']}`",
        f"- dry_run: `{report['dry_run']}`",
        f"- queue_root: `{report['queue_root']}`",
        f"- packets_seen: `{report['packets_seen']}`",
        f"- allowed_count: `{report['allowed_count']}`",
        f"- blocked_count: `{report['blocked_count']}`",
        f"- requires_special_approval_count: `{report['requires_special_approval_count']}`",
        f"- not_allowed_count: `{report['not_allowed_count']}`",
        f"- acceptance_checks_executed: `{report['acceptance_checks_executed']}`",
        f"- codex_app_server_used: `{report['codex_app_server_used']}`",
        f"- automatic_execution_enabled: `{report['automatic_execution_enabled']}`",
        "",
        "## Packets",
        "",
    ]

    if not report["entries"]:
        lines.append("- No approved packet JSON files found.")
    else:
        for entry in report["entries"]:
            task_id = entry.get("task_id") or entry.get("packet_path")
            lines.append(f"- `{task_id}`: {entry.get('classification_status', 'unknown')}")
            if entry.get("plan_path"):
                lines.append(f"  - plan: `{entry['plan_path']}`")
            if entry.get("handoff_prompt_path"):
                lines.append(f"  - handoff_prompt: `{entry['handoff_prompt_path']}`")
            for error in entry.get("errors", []):
                lines.append(f"  - error: {error}")

    lines.extend(
        [
            "",
            "## Safety",
            "",
            "This report was generated by the local dry-run runner only. It did not execute acceptance checks, invoke Codex, call Codex app-server, create branches, create worktrees, move packets, start workers, or call network services.",
            "",
        ]
    )
    return "\n".join(lines)


def write_reports(queue_root: str | Path, report: Mapping[str, Any]) -> dict[str, str]:
    root = ensure_queue_directories(queue_root)
    reports_dir = root / "reports"
    run_json = reports_dir / f"dry_run_report_{report['run_id']}.json"
    latest_json = reports_dir / "latest_dry_run_report.json"
    latest_md = reports_dir / "latest_dry_run_report.md"
    write_json(run_json, report)
    write_json(latest_json, report)
    write_text(latest_md, render_markdown_report(report))
    return {
        "run_report_json": str(run_json),
        "latest_report_json": str(latest_json),
        "latest_report_md": str(latest_md),
    }

